# 全局参数如下

pid_file ../conf_xwf/mosquitto.pid
# 指定PID文件的路径。默认值为 /var/run/mosquitto/mosquitto.pid。

allow_anonymous true
# 指定是否允许匿名访问。默认值为 true。

listener 1883 0.0.0.0
# 指定监听的网络接口和端口号。0.0.0.0表示监听所有IP；127.0.0.1表示只监听


