# 全局参数如下

pid_file ../conf_xwf/mosquitto.pid
# 指定PID文件的路径。默认值为 /var/run/mosquitto/mosquitto.pid。

allow_anonymous true
# 指定是否允许匿名访问。默认值为 true。

listener 1883 0.0.0.0
# 指定监听的网络接口和端口号。0.0.0.0表示监听所有IP；127.0.0.1表示只监听本机

log_dest file ../conf_xwf/log/mosquitto.log
# 指定日志输出的目标。默认值为 stderr。log_dest stderr|syslog|stdout|<path>表示可以输出到这几个地方

log_type all
#log_type none|information|notice|warning|debug|subscribe|unsubscribe|websockets
# 指定日志输出的类型。默认值为 information。

log_timestamp true
# 指定日志消息是否包含时间戳。默认值为 true。

log_timestamp_format %Y-%m-%d %H:%M:%S 
# 日志显示格式，目前不支持毫秒级显示%Y-%m-%d %H:%M:%S.%s [%l] 表示日志级别，目前不支持
